language: go
sudo: required
dist: trusty

services:
  - docker

go:
  - 1.7.x
  - 1.8.x
  - tip

go_import_path: github.com/Crazykev/dev-tools/go-examples

install:
  - networking/cnitool/install-cni.sh

script:
  - networking/cnitool/test-cnitool.sh
