# Copy of pod.yaml without file extension for test
apiVersion: v1
kind: Pod
metadata:
  name: nginx1
  labels:
    name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
        - name: nginx-log
          mountPath: /var/log/nginx
  - name: log-collect
    image: busybox
    args: [/bin/sh, -c, 'tail -n+1 -f /var/log/access.log']
    volumeMounts:
        - name: nginx-log
          mountPath: /var/log
  volumes:
      - name: nginx-log
        emptyDir: {}
