apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0004
  labels:
    type: test-pv 
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
      path: /root/storage/pv4/
