---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
  labels:
    type: test-pv 
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
      path: /root/storage/pv1/
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0002
  labels:
    type: test-pv 
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
      path: /root/storage/pv2/
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0003
  labels:
    type: test-pv 
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
      path: /root/storage/pv3/
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: "nginx"
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: gcr.io/google_containers/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      selector:
          matchLabels:
            type: test-pv
      resources:
        requests:
          storage: 1Gi
